### ISSUE TITLE
simpler static files example

### ISSUE THREAD

**Issue by nhooyr** [gowebexamples/gowebexamples#1]
```go
// static-files.go
package main

import "net/http"

func main() {
	fs := http.FileServer(http.Dir("."))
	http.Handle("/static/", fs)

	http.ListenAndServe(":8080", nil)
}
```

**Comment by philippta** [comment]
I like the cleverness and simplicity behind this snipped. However I think it hides the clear path, how the files are served.  One might start looking at `http.FileServer(http.Dir("."))`, thinking all files in the current directory are exposed (including the go app itself), which is basically true. However the `http.Handle("/static/", fs)` implicitly guards it, so only files in the subdirectory "static" can be served.

Thank you for the submission.
